version: '3'

services:
  vscode:
    image: linuxserver/code-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Los_Angeles
      - PASSWORD=${VSCODE_PASSWORD} #optional
        #- HASHED_PASSWORD= #optional
        #- SUDO_PASSWORD=password #optional
        #- SUDO_PASSWORD_HASH= #optional
        #- PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/workspace #optional
    volumes:
      - /data/vscode/${VSCODE_USER}/config:/config:rw
      - /data/vscode/${VSCODE_USER}/workspace:/workspace:rw
    ports:
      - 8090:8443
    restart: unless-stopped
