version: '3'
services:
  vscode:
    image: linuxserver/code-server:latest
    volumes:
      - /data/vscode/$VSCODE_USER}/project:/home/coder/project
      - /code/vscode/${VSCODE_USER}/config:/home/coder/.local/share/code-server
    ports:
      - "8443:8443"
    command: code-server --auth password --port 8443 --disable-telemetry /home/coder/project
    environment:
      PASSWORD: "${VSCODE_PASSWORD}"
    restart: unless-stopped

